### ISSUE TITLE
Custom Model

### ISSUE THREAD

**Issue by ssetty** [merantix/picasso#46]
* picasso version:
* Python version:
* Operating System:

### Description
How do we visualize custom models created by keras tensorflow?
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by maths-qureshi** [comment]
Hi,

I am trying to visualize the output of a Unet and have provided the config.py and model.py. I also have the Unet model as a dump but I keep getting the following errors:
Traceback (most recent call last):
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\320035951\AppData\Local\conda\conda\envs\deeplearning\Scripts\flask.exe\__main__.py", line 9, in <module>
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\flask\cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\flask\cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\flask\cli.py", line 767, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\flask\cli.py", line 293, in __init__
    self._load_unlocked()
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\flask\cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\flask\cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\flask\cli.py", line 235, in locate_app
    __import__(module_name)
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\picasso\__init__.py", line 40, in <module>
    import picasso.picasso
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\picasso\picasso.py", line 95, in <module>
    app.config['MODEL_LOAD_ARGS'])
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\picasso\models\base.py", line 29, in load_model
    model.load(**model_load_args)
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\picasso\models\keras.py", line 46, in load
    self._model = model_from_json(model_json)
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\site-packages\keras\engine\saving.py", line 490, in model_from_json
    config = json.loads(json_string)
  File "c:\users\320035951\appdata\local\conda\conda\envs\deeplearning\lib\json\__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'

**Comment by yinawang28** [comment]
After installation (pip install on Mac OS, python 3.6) and run flask:
Error: The file/path provided (picasso) does not appear to exist. Please verify the path is correct. If app is not on PYTHONPATH, ensure the extension is .py 

This should be an ImportError according to https://stackoverflow.com/questions/41913345/flask-error-the-file-path-provided-does-not-appear-to-exist-although-the-file 

After check the console script, I didn't find the picasso.commands:main.
