### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by lezhang0912** [merantix/picasso#47]
* picasso version:0.2.0
* Python version:3.6.5
* Operating System:ubuntu16.04
AttributeError
AttributeError: module 'keras.applications.imagenet_utils' has no attribute 'CLASS_INDEX'

Traceback (most recent call last):
  File "/home/zhangle/virtual_python_env/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/zhangle/virtual_python_env/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/zhangle/virtual_python_env/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zhangle/virtual_python_env/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/zhangle/virtual_python_env/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zhangle/virtual_python_env/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zhangle/virtual_python_env/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zhangle/virtual_python_env/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/zhangle/virtual_python_env/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zhangle/virtual_python_env/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zhangle/virtual_python_env/venv/lib/python3.6/site-packages/picasso/picasso.py", line 336, in select_files
    settings=session['settings'])
  File "/home/zhangle/virtual_python_env/venv/lib/python3.6/site-packages/picasso/visualizations/class_probabilities.py", line 20, in make_visualization
    filtered_predictions = self.model.decode_prob(predictions)
  File "/home/zhangle/virtual_python_env/venv/lib/python3.6/site-packages/picasso/examples/keras-vgg16/model.py", line 39, in decode_prob
    classes = imagenet_utils.CLASS_INDEX
AttributeError: module 'keras.applications.imagenet_utils' has no attribute 'CLASS_INDEX'

**Comment by lezhang0912** [comment]
who meet this error?Could you give me some advices?Thanks
